apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-backend
  template:
    metadata:
      labels:
        app: fullstack-backend
    spec:
      containers:
      - name: backend
        image: fullstack-backend:latest
        ports:
        - containerPort: 5055
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:Monday%4001@postgres-service:5432/cicd?sslmode=disable
---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-backend-service
spec:
  type: NodePort
  ports:
  - port: 5055
    nodePort: 30055
  selector:
    app: fullstack-backend
