apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstack-frontend
  template:
    metadata:
      labels:
        app: fullstack-frontend
    spec:
      containers:
      - name: frontend
        image: fullstack-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fullstack-frontend-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: fullstack-frontend
